### ISSUE TITLE
FFI Loader cannot locate argon2_wrap on Mac OSX

### ISSUE THREAD

**Issue by tgoddard** [technion/ruby-argon2#3]
From clean git checkout, submodules installed, running setup then console:

```
Tims-MBP:ruby-argon2 timgoddard$ bin/setup 
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using ffi 1.9.10
Using ffi-compiler 0.1.3
Using argon2 0.1.1 from source at .
Using ast 2.2.0
Using parser 2.2.3.0
Using astrolabe 1.3.1
Using bundler 1.10.5
Using docile 1.1.5
Using json 1.8.3
Using simplecov-html 0.10.0
Using simplecov 0.11.1
Using codeclimate-test-reporter 0.4.8
Using minitest 5.8.3
Using powerpack 0.1.1
Using rainbow 2.0.0
Using ruby-progressbar 1.7.5
Using tins 1.6.0
Using rubocop 0.35.1
Bundle complete! 6 Gemfile dependencies, 19 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
cc -std=c89 -pthread -O3 -Wall -g -march=native -dynamiclib -install_name @rpath/libargon2_wrap.dylib ../phc-winner-argon2/src/argon2.c ../phc-winner-argon2/src/core.c ../phc-winner-argon2/src/blake2/blake2b.c ../phc-winner-argon2/src/thread.c ../phc-winner-argon2/src/encoding.c argon_wrap.c ../phc-winner-argon2/src/opt.c -o libargon2_wrap.dylib
Tims-MBP:ruby-argon2 timgoddard$ bin/console 
/Users/timgoddard/.rvm/gems/ruby-2.2.1/gems/ffi-compiler-0.1.3/lib/ffi-compiler/loader.rb:21:in `find': cannot find 'argon2_wrap' library (LoadError)
	from /Users/timgoddard/Repo/ruby-argon2/lib/argon2/ffi_engine.rb:8:in `<module:Ext>'
	from /Users/timgoddard/Repo/ruby-argon2/lib/argon2/ffi_engine.rb:6:in `<module:Argon2>'
	from /Users/timgoddard/Repo/ruby-argon2/lib/argon2/ffi_engine.rb:4:in `<top (required)>'
	from /Users/timgoddard/Repo/ruby-argon2/lib/argon2.rb:2:in `require'
	from /Users/timgoddard/Repo/ruby-argon2/lib/argon2.rb:2:in `<top (required)>'
	from bin/console:4:in `require'
	from bin/console:4:in `<main>'
```

The same issue appears with an installed gem. Not sure it's finding the dylib file.

**Comment by technion** [comment]
This is an El Capitan issue. See #1 and the README links for discussion.
While it is a regrettable annoyance, I don't have a lot of room to move around fixing it.

**Comment by tgoddard** [comment]
OK, it's not just El Capitan then - I'm on Yosemite still.

**Comment by technion** [comment]
@tgoddard in that case, there *might* be something else going on in your case, but I would need it very clearly identified, preferably with a PR, before I could do anything with it (as someone without a Mac).
